/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ıqpuzzlerpro;

import java.awt.BorderLayout;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author Dervis
 */
public class HowToPlay extends javax.swing.JPanel {

    /*JFrame frame;
    Menu1 menu;*/
    public HowToPlay() {
        /*this.frame = frame;
        this.menu = menu;*/
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(2000, 1000));
        setMinimumSize(new java.awt.Dimension(2000, 1000));
        setPreferredSize(new java.awt.Dimension(2000, 1000));
        setLayout(null);

        back.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 0, 51));
        back.setText("Back");
        back.setContentAreaFilled(false);
        add(back);
        back.setBounds(50, 50, 80, 50);

        jScrollPane1.setAlignmentX(5.0F);
        jScrollPane1.setAlignmentY(1.0F);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("  How To Play:\n\n              The game has boards and twelve pieces.\n  Players should select a piece and place it to board's \n  empty places. There shouldn't be any piece at outside \n  of the board to win. \n              The player can rotate or flip pieces to place \n  them in proper places.\n              To rotate the piece,user should use the scroll up. \n              Each scroll rotates piece 90 degrees around \n  axises once.  Also,to flip piece, user can use the mouse \n  again but it should be scrolled down. \n              Each scroll down, flip the piece once. \n              To move piece user should press on the piece,\n  drag it to the desired place and drop. When players fill all\n  empty places with correctly pieces, the game will be finished.\n              The game offers users hints to help them.");
        jTextArea1.setAlignmentX(200.0F);
        jTextArea1.setAlignmentY(200.0F);
        jTextArea1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 0, 0), null, new java.awt.Color(0, 255, 204), new java.awt.Color(0, 204, 204)));
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(280, 160, 510, 460);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ıqpuzzlerpro/Images/How_to_play_1600x900.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, 0, 1600, 900);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables

    public JButton getBackButton()
    {
        return back;
    }
}
